Implement Third Page of Core Demo
microsoft/WinObjC-Samples pull request #32
Opened 2017-04-26 21:46 UTC by MSFTFox

Implement third page of core demo. This page shows off various blend modes with images.

2017-04-26 21:48 UTC, DHowett-MSFT approved these changes
same question about PD

2017-04-26 21:48 UTC, DHowett-MSFT commented on Scenarios/CGCT/CGCT/DemoScenarioImages.m
> +            CGRect pane = CGRectMake(x * bounds.size.width, y * bounds.size.height, catSize, catSize * aspectRatio);
`cat` :laughing:

2017-04-26 21:48 UTC, DHowett-MSFT commented on Scenarios/CGCT/CGCT/DemoScenarioImages.m
> +        patternImage = [UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"sunset" ofType:@"png"]];
nit: not a pattern, and ivars usually begin with `_`

2017-04-26 21:48 UTC, DHowett-MSFT commented on Scenarios/CGCT/CGCT/DemoScenarioImages.h
> +- (void)drawDemoIntoContext:(CGContextRef)context withFrame:(CGRect)bounds;
technically you need not specify this method

2017-04-26 21:51 UTC, DHowett-MSFT requested changes

2017-04-26 21:51 UTC, DHowett-MSFT commented on Scenarios/CGCT/CGCT/DemoScenarioImages.m
> +            CGContextDrawPath(context, kCGPathFill);
youuuuuu could just CGContextFillRect

2017-04-26 21:51 UTC, DHowett-MSFT commented on Scenarios/CGCT/CGCT/DemoScenarioImages.m
> +            CGContextSetBlendMode(context, blendModes[blendModeIndex]);
also, the GState is never being saved, Each successive image is being drawn in the previous color plate's blend mode ...

2017-04-26 21:52 UTC, rajsesh requested changes

2017-04-26 21:52 UTC, rajsesh-msft commented on Scenarios/CGCT/CGCT/DemoScenarioImages.m
> +    CGFloat fillColors[48];
2x2x2x2x4 = 64.

2017-04-27 00:26 UTC, DHowett-MSFT approved these changes

2017-04-27 00:49 UTC, rajsesh approved these changes

2017-04-27 08:34 UTC, merged